name: Build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build-photonlib-docker:
    runs-on: ubuntu-22.04
    container: wpilib/aarch64-cross-ubuntu:bullseye-22.04
    name: "Photonlib - Build Docker - LinuxArm64"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Config Git
        run: |
          git config --global --add safe.directory /__w/photonvision-xtables/photonvision-xtables
      - name: Build PhotonLib
        run: ./gradlew photon-targeting:build photon-lib:build -Ponlylinuxarm64 -i -x test
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: photonlib-linuxarm64
          path: build/libs/*linuxarm64*.jar
