name: Build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-photonlib-docker:
    runs-on: ubuntu-22.04
    container: wpilib/aarch64-cross-ubuntu:bullseye-22.04
    name: "Photonlib - Build Docker - LinuxArm64"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Config Git
        run: |
          git config --global --add safe.directory /__w/photonvision/photonvision
      - name: Build PhotonLib
        run: ./gradlew photon-targeting:build photon-lib:build -Ponlylinuxarm64 -i -x test
      - name: Publish
        run: ./gradlew photon-lib:publish photon-targeting:publish -Ponlylinuxarm64
        env:
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
      - run: ./gradlew photon-lib:publish photon-targeting:publish -PcopyOfflineArtifacts -Ponlylinuxarm64
      - uses: actions/upload-artifact@v4
        with:
          name: maven-linuxarm64
          path: build/outputs
